routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');
Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/password', function(){
    return redirect()->route('password.update');
});
Route::get('/resetcomplete', function(){
    Auth::logout();
    return view('auth.passwords.resetcomplete');
});

Route::get('terminos', function(){
    return response()->view('terminos.index', [], 200);
});

// Route::get('/', function(){
//     Route::auth();
// });

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

/*
|--------------------------------------------------------------------------
| Ruta para probar el esquema principal de las vistas
|--------------------------------------------------------------------------
*/
Route::get('/esquema', function(){
    return view('esquema.index');
});

/*
|--------------------------------------------------------------------------
| Rutas para usuarios autenticados
|--------------------------------------------------------------------------
*/
Route::middleware(['auth'])->group(function(){

    /*
    | Ruta para el dashboard
    |*/
    // Route::get('/', function(){
    //     return view('esquema.index');
    // });
    // Route::get('/dashboard', function(){
    //     return view('dashboard.index');
    // });
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
    Route::post('/dashboard', 'DashboardController@graficasDatos')->name('dashboard.graficasDatos');

    /*
    | Ruta para el perfil del usuario
    |*/
    Route::resource('/perfil', 'PerfilController')->only(['index', 'show', 'edit', 'update']);
    Route::post('/perfil/emergencia', 'PerfilController@cerradoEmergencia')->name('perfil.cerradoemergencia');


    /*
    | CRUD para editar a los usuarios y sus tipos
    |*/
    Route::resource('/usuarios', 'UsuariosController');
    Route::resource('/tipos', 'UsuariosTipoController');

    /*
    | Ruta para los detalles de usuario tienda
    |*/
    Route::post('/usuarios/modaldetalles', 'UsuariosController@modalDetalles')->name('usuarios.modalDetalles');
    Route::post('/usuarios/graficos', 'UsuariosController@graficasDinamicas')->name('usuarios.graficasDinamicas');

    /*
    | CRUD para editar a los productos y sus categorias
    |*/
    Route::resource('/categorias', 'CategoriasProductoController', ['as' => 'tienda']);
    Route::resource('/productos', 'ProductosController', ['as' => 'tienda']);
    Route::resource('/adicionales', 'AdicionalesController', ['as' => 'tienda']);
     /*
    | ordenar productos y categorias
    |*/
    Route::get('/productos/ordenar/{id}', 'ProductosController@productosDeCategoria')->name('ordenar_productos.edit');
    Route::post('/productos/ordenar', 'ProductosController@productosDeCategoriaGuardar')->name('ordenar_productos.guardar');
    Route::post('/categorias/ordenar', 'CategoriasProductoController@CategoriaGuardarOrden')->name('ordenar_categorias.guardar');

    Route::resource('/coordenadas', 'CoordenadasController');
    Route::get('/coordenadas/obtener/{id}', 'CoordenadasController@obtener');

    /*
    |   Ruta que recibe el token para las notificaciones web
    */
    Route::post('tokenfcm/recibir', 'FCMtoken@recibirToken')->name('recibir.token');

    /*
    |   Ruta que muestra los pedidos
    */
    
    Route::get('pedidos/activos/{estatus?}', 'PedidosController@activos')->name('tienda.pedidos.activos');


    // Route::get('pedidos/historico', 'PedidosController@historico')->name('tienda.pedidos.historico');
    Route::get('pedidos', 'PedidosController@historico')->name('tienda.pedidos.historico');
    Route::get('pedidos/{id?}', 'PedidosController@pedido')->name('tienda.pedidos.pedido');
    Route::get('pedidos/aceptar/{id?}', 'PedidosController@aceptarPedido')->name('tienda.pedidos.aceptar');
    Route::get('pedidos/cancelar/{id?}', 'PedidosController@cancelarPedido')->name('tienda.pedidos.cancelar');
    Route::get('pedidos/enviar/{id?}', 'PedidosController@enviarPedido')->name('tienda.pedidos.enviar');
    Route::get('pedidos/entregar/{id?}', 'PedidosController@entregarPedido')->name('tienda.pedidos.entregar');
    Route::get('pedidos/listo/{id?}', 'PedidosController@listoEnviar')->name('tienda.pedidos.listo');
    
    /*
    |   Ruta que muestra los errores del sistema
    */
    Route::get('error', 'ErrorController@index')->name('error.index');
    Route::get('error/{id?}', 'ErrorController@buscar')->name('error.buscar');

    /*
    | CRUD para mensajes de ayuda
    |*/
    Route::get('/mensaje', 'MensajesAyudaController@index')->name('error.mensajes_ayuda');
    Route::get('/mensaje/{id}', 'MensajesAyudaController@edit')->name('mensajes_ayuda.edit');
    Route::post('/mensaje/{id}', 'MensajesAyudaController@update')->name('mensajes_ayuda.update');

    /*
    | CRUD para etiquetas
    |*/
    Route::get('/etiqueta', 'EtiquetasController@index')->name('error.etiquetas');
    Route::post('/etiqueta', 'EtiquetasController@store')->name('etiquetas.store');
    Route::get('/etiqueta/{id}', 'EtiquetasController@edit')->name('etiquetas.edit');
    Route::post('/etiqueta/{id}', 'EtiquetasController@update')->name('etiquetas.update');
    /*
    | Productos orden
    |*/
    // Route::get('/orden', 'ProductoCategoriaController@index')->name('productoCategoriaOrden.index');

    /*
    | Control de versiones
    |*/
    Route::resource('/version', 'VersionController');

    /*
    | Ubicación de motos
    |*/
    Route::get('/ubicacionmotos', function(){
        return view("maps.ubicamotos");
    })->name('ubicacion.motos');
    Route::get('/coordenadas/motorizados/todos', 'CoordenadasController@coordenadasMotorizados')->name('coordenadas.motorizados');
    Route::get('/coordenadas/tiendas/todos', 'CoordenadasController@coordenadasTiendas')->name('coordenadas.tiendas');
    Route::get('/coordenadas/pedidos/todos', 'CoordenadasController@coordenadasPedidos')->name('coordenadas.pedidos');

    /*
    | Ubicación de pedidos pendiente para cada tienda
    |*/
    Route::get('/ubicar/pedidos', 'UbicarPedidosController@index')->name('ubicar.pedidos.index');
    Route::get('/ubicar/pedidos/obtener', 'UbicarPedidosController@obtener')->name('ubicar.pedidos.obtener');
    Route::get('/ubicar/pedidos/coord/tienda', 'UbicarPedidosController@coordenadasTienda')->name('ubicar.pedidos.coord.tienda');

    Route::get('/administrar/pedido', 'Administrador\PedidosController@obtener')->name('administrar.pedidos');
    Route::post('/administrar/pedido', 'Administrador\PedidosController@modificar')->name('administrar.pedidos.modificar');
    
    Route::get('culqi', 'CulqiController@index')->name('culqi');

    /*
    | Promociones
    |*/
    Route::resource('promocion/banner', 'BannerController');
    Route::resource('promocion/notificaciones', 'NotificacionesController');

    /*
    | Emojis
    |*/
    Route::resource('emojis', 'EmojisController');

    /*
    | Ruta de Cambio de login
    |*/
    Route::get('/cambio/login/{id}', 'CambioLoginController@index')->name('cambio.login');

    /*
    | Ruta de Pruebas
    |*/
    Route::get('/pruebas', function(){

        // $mapsApiKey="AIzaSyC5WO_983jAxhg6v-_AHH94FXMZzFUXDVo";
        // $coordTienda = [
        //     "lat" => -12.102584,
        //     "long" => -77.025892
        // ];

        // $coordCliente = [
        //     "lat" => -12.099347,
        //     "long" => -76.998089
        // ];

        // // $coordCliente = [
        // //     "lat" => -12.102179,
        // //     "long" => -77.021896
        // // ];

        // $ruta= "https://maps.googleapis.com/maps/api/directions/json?origin=". $coordTienda['lat'] .",". $coordTienda['long'] ."&destination=". $coordCliente['lat'] .",". $coordCliente['long'] ."&units=metric&key=". $mapsApiKey ."&alternatives=true";
        
        // $json = file_get_contents($ruta);
        // $obj = json_decode($json);

        // $cantRutasAlternativas = count($obj->routes);
        // $rutaMenor = 99999;

        // for($i = 0; $i < $cantRutasAlternativas; $i++){
        //     $j = $i;
        //     echo "Ruta " . ($j+1) . " => ". $obj->routes[$i]->legs[0]->distance->text . "<br> ";
        //     $explodeDistacia = explode(" ", $obj->routes[$i]->legs[0]->distance->text);
        //     $cantRecorrida = $explodeDistacia[0]; 
            

        //     if($cantRecorrida <= $rutaMenor){
        //         $rutaMenor = $cantRecorrida;
        //         $unidadMedida = $explodeDistacia[1];
        //     }
            
        // }

        // echo $rutaMenor . " - " . $unidadMedida;

        $horaActual = now();
        $horaEnBBDD = now()->addMinutes(45);


        $respuesta = array(
            "Hora actual" => $horaActual,
            "+ 45 minutos" => $horaEnBBDD,
            "Diferencia" => $horaActual->diffInMinutes($horaEnBBDD),
        );

        return response()->json($respuesta);
    });


});

resources/views/esquema/contenido.blade.php
<div class="app-content">
					<div class="section">
                    {{---
                    	<ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Pages</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Empty page</li>
                        </ol>
                    ---}}
                        @yield('contenido')
					</div>
				</div>

resources/views/esquema/index.blade.php
@extends('esquema.esquema')

@section('css')
@endsection

@section('contenido')
                        <div class="row">
							<div class="col-md-12">
								<div class="card">
									<div class="card-body">
										your text hereAqui
									</div>
								</div>
							</div>
						</div>
@endsection

@section('javascript')
@endsection

resources/views/esquema/menu_izquierdo.blade.php
@php
	$colorMenu = '<aside class="app-sidebar">';
@endphp
@usuario('root')
	<style>
	{{--
	.app-sidebar {
		background:linear-gradient(#f7f7fa, #5d61bf) !important;
	}
	--}}
	.app-sidebar {
		background:#673AB7 !important;
	}
	</style>
@endusuario
<aside class="app-sidebar">
						<div>
							<img src="{{Auth::user()->foto}}" alt="" width="230px">
						</div>
					<ul class="side-menu">
						<li class="slide">
							<a class="side-menu__item" href="{{route('dashboard.index')}}"><i class="side-menu__icon fa fa-desktop"></i><span class="side-menu__label">Dashboard</span></i></a>
						</li>
						@usuario('root')
						{{--  <li class="slide">
							<a class="side-menu__item" href="{{route('culqi')}}"><i class="side-menu__icon fa fa-desktop"></i><span class="side-menu__label">Culqi</span></i></a>
						</li>  --}}
						<li class="slide">
							<a class="side-menu__item"  data-toggle="slide" href="#"><i class="side-menu__icon fa fa-users"></i><span class="side-menu__label">Usuarios</span><i class="angle fa fa-angle-right"></i></a>
							<ul class="slide-menu">
								<li><a class="slide-item" href="{{route('usuarios.index')}}"><span>Usuarios</span></a></li>
								<li><a class="slide-item" href="{{route('usuarios.index')}}/?txtBuscar=motorizado"><span>Motorizados</span></a></li>
								<li><a class="slide-item" href="{{route('usuarios.index')}}/?txtBuscar=tienda"><span>Comercios</span></a></li>
								<li><a class="slide-item" href="{{route('tipos.index')}}"><span>Tipos</span></a></li>
							</ul>
						</li>
						@endusuario
						@usuario('tienda')
						{{--
						<li class="slide">
							<a class="side-menu__item" href="{{route('perfil.edit', ['id' =>  Auth::user()->id])}}"><i class="side-menu__icon fa fa-home"></i><span class="side-menu__label">Comercio</span></i></a>
						</li>
						--}}
						@if(Session::get('numero_marcas'))
						@php($lasmarcas = Session::get('las_marcas'))
						<li class="slide is-expanded">
							<a class="side-menu__item" href="#"><i class="side-menu__icon fa fa-gears"></i><span class="side-menu__label">Mis comercios</span><i class="angle fa fa-angle-right"></i></a>
						@foreach($lasmarcas as $marca)
							@if($marca['id']==auth()->user()->id)
								@php($activo = "active")
							@else
								@php($activo = "")
							@endif
							<ul class="slide-menu">
								<li><a class="slide-item {{$activo}}" href="{{route('cambio.login', ['id' => $marca['id']])}}"><span>{{$marca['name']}}</span></a></li>
							</ul>
						@endforeach
						@endif
						<li class="slide">
							<a class="side-menu__item"  data-toggle="slide" href="#"><i class="side-menu__icon fa fa-list"></i><span class="side-menu__label">Carta</span><i class="angle fa fa-angle-right"></i></a>
							<ul class="slide-menu">
								<li><a class="slide-item" href="{{route('tienda.categorias.index')}}"><span>Categorías</span></a></li>
								<li><a class="slide-item" href="{{route('tienda.productos.index')}}"><span>Productos</span></a></li>
								{{---
								<li><a class="slide-item" href="{{route('tienda.adicionales.index')}}"><span>Adicionales</span></a></li>
								---}}
							</ul>
						</li>
						@endusuario
						@usuarios(['tienda','root'])
						<li class="slide">
							<a class="side-menu__item"  data-toggle="slide" href="#"><i class="side-menu__icon fa fa-send-o"></i><span class="side-menu__label">Pedidos</span><i class="angle fa fa-angle-right"></i></a>
							<ul class="slide-menu">
								<li><a class="slide-item" href="{{route('tienda.pedidos.activos')}}/activos"><span>Activos</span></a></li>
								<li><a class="slide-item" href="{{route('ubicar.pedidos.index')}}"><span>En mapa</span></a></li>
							</ul>
						</li>
						@endusuario
						@usuario('root')
						<li class="slide">
							<a class="side-menu__item"  data-toggle="slide" href="#"><i class="side-menu__icon fa fa-star-o"></i><span class="side-menu__label">Promociones</span><i class="angle fa fa-angle-right"></i></a>
							<ul class="slide-menu">
								<li><a class="slide-item" href="{{route('banner.index')}}"><span>Banner</span></a></li>
								<li><a class="slide-item" href="{{route('notificaciones.index')}}"><span>Notificaciones</span></a></li>
							</ul>
						</li>
						<li class="slide">
							<a class="side-menu__item"  data-toggle="slide" href="#"><i class="side-menu__icon fa fa-bolt"></i><span class="side-menu__label">Emoticones</span><i class="angle fa fa-angle-right"></i></a>
							<ul class="slide-menu">
								<li><a class="slide-item" href="{{route('emojis.index')}}"><span>Emojis</span></a></li>
							</ul>
						</li>
						<li class="slide">
							<a class="side-menu__item"  data-toggle="slide" href="#"><i class="side-menu__icon fa fa-gears"></i><span class="side-menu__label">Sistema</span><i class="angle fa fa-angle-right"></i></a>
							<ul class="slide-menu">
								<li><a class="slide-item" href="{{route('error.index')}}"><span>Reporte de errores</span></a></li>
							</ul>
							<ul class="slide-menu">
								<li><a class="slide-item" href="{{route('error.mensajes_ayuda')}}"><span>Mensajes de ayuda</span></a></li>
							</ul>
							<ul class="slide-menu">
								<li><a class="slide-item" href="{{route('error.etiquetas')}}"><span>Etiquetas</span></a></li>
							</ul>
							<ul class="slide-menu">
								<li><a class="slide-item" href="{{route('version.index')}}"><span>Control de versión</span></a></li>
							</ul>
							<ul class="slide-menu">
								<li><a class="slide-item" href="{{route('ubicacion.motos')}}"><span>Ubicación motorizados</span></a></li>
							</ul>
						</li>
						@endusuario
						<li class="slide">
							<a class="side-menu__item" href="{{route('logout')}}"><i class="side-menu__icon fa fa-power-off"></i><span class="side-menu__label">Cerrar sesión</span></i></a>
						</li>
						{{---
						<li class="slide">
							<a class="side-menu__item"  data-toggle="slide" href="#"><i class="side-menu__icon fa fa-desktop"></i><span class="side-menu__label">Dashboard</span><i class="angle fa fa-angle-right"></i></a>
							<ul class="slide-menu">
								<li><a class="slide-item"  href="index.html"><span>Sales Dashboard</span></a></li>
								<li><a class="slide-item" href="index2.html"><span>Finance Dashboard</span></a></li>
								<li><a class="slide-item" href="index3.html"><span>Marketing Dashboard</span></a></li>
								<li><a class="slide-item" href="index4.html"><span>Social Dashboard</span></a></li>
								<li><a class="slide-item" href="index5.html"><span>HR Dashboard</span></a></li>
							</ul>
						</li>
						<li>
							<a class="side-menu__item" href="widgets.html"><i class="side-menu__icon fa fa-flask"></i><span class="side-menu__label">Widgets</span></a>
						</li>
						<li class="slide">
							<a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fa fa-tasks"></i><span class="side-menu__label">UI Elements</span><i class="angle fa fa-angle-right"></i></a>
							<ul class="slide-menu">
								<li><a href="elements.html" class="slide-item"> Elements</a></li>
								<li><a href="buttons.html" class="slide-item"> Buttons</a></li>
								<li><a href="toastr.html" class="slide-item"> Toastr</a></li>
								<li><a href="calender.html" class="slide-item"> Calendar</a></li>
								<li><a href="rangesliders.html" class="slide-item"> Rangeslider</a></li>
								<li><a href="modals.html" class="slide-item"> Modals</a></li>
								<li><a href="timeline.html" class="slide-item"> Timeline</a></li>
								<li><a href="invoice.html" class="slide-item"> Invoice</a></li>
								<li><a href="users.html" class="slide-item"> Users List</a></li>
								<li><a href="mailinbox.html" class="slide-item"> Mail-inbox</a></li>
								<li><a href="mail-compose.html" class="slide-item"> Mail-Compose</a></li>
							</ul>
						</li>
						<li class="slide">
						    <a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fa fa-paw"></i><span class="side-menu__label">Icons</span><i class="angle fa fa-angle-right"></i></a>
							<ul class="slide-menu">
								<li><a href="icons-ion.html" class="slide-item"> Ion Icons</a></li>
								<li><a href="icons-fontawesome.html" class="slide-item"> Font Awesome</a></li>
								<li><a href="icons-feather.html" class="slide-item"> Feather Awesome</a></li>
								<li><a href="icons-materialdesign.html" class="slide-item"> Material Design</a></li>
								<li><a href="icons-themify.html" class="slide-item"> Themify</a></li>
								<li><a href="icons-simpleline.html" class="slide-item"> Simple line</a></li>
								<li><a href="icons-pe7.html" class="slide-item"> pe7</a></li>
								<li><a href="icons-flag.html" class="slide-item"> Flag Icons</a></li>
								<li><a href="icons-weather.html" class="slide-item"> Weather Icons</a></li>
								<li><a href="icons-typicons.html" class="slide-item"> Typicons</a></li>
							</ul>
						</li>
						<li class="slide">
							<a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fa fa-table"></i><span class="side-menu__label">Tables</span><i class="angle fa fa-angle-right"></i></a>
							<ul class="slide-menu">
								<li><a href="table.html" class="slide-item">Basic Tables</a></li>
								<li><a href="datatables.html" class="slide-item"> Data Tables</a></li>
							</ul>
						</li>
						<li class="slide">
							<a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fa fa-file-text"></i><span class="side-menu__label">Forms</span><i class="angle fa fa-angle-right"></i></a>
							<ul class="slide-menu">
								<li><a href="formelements.html" class="slide-item"> Form Elements</a></li>
								<li><a href="formadvanced.html" class="slide-item"> Advanced Form</a></li>
								<li><a href="formeditor.html" class="slide-item"> Form Editor</a></li>
							</ul>
						</li>
						<li class="slide">
							<a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fa fa-bar-chart"></i><span class="side-menu__label">Charts</span><i class="angle fa fa-angle-right"></i></a>
							<ul class="slide-menu">
								<li><a href="chartjs.html" class="slide-item">Chart Js</a></li>
								<li><a href="flotcharts.html" class="slide-item"> Flot Charts</a></li>
								<li><a href="barcharts.html" class="slide-item"> Bar Charts</a></li>
								<li><a href="echart.html" class="slide-item"> ECharts</a></li>
								<li><a href="chartist.html" class="slide-item"> Chartist</a></li>
								<li><a href="morris.html" class="slide-item"> Morris Charts</a></li>
								<li><a href="othercharts.html" class="slide-item"> Other Charts</a></li>
							</ul>
						</li>
						<li class="slide">
							<a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fa fa-map"></i><span class="side-menu__label">Maps</span><i class="angle fa fa-angle-right"></i></a>
							<ul class="slide-menu">
								<li><a href="maps.html" class="slide-item"> Google Maps</a></li>
								<li><a href="vector-map.html" class="slide-item">Vector Maps</a></li>
							</ul>
						</li>
						<li class="slide">
							<a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fa fa-pie-chart"></i><span class="side-menu__label">Pages</span><i class="angle fa fa-angle-right"></i></a>
							<ul class="slide-menu">
								<li><a href="profile.html" class="slide-item"> Profile</a></li>
								<li><a href="pricing-tables.html" class="slide-item"> Pricing Tables</a></li>
								<li><a href="gallery.html" class="slide-item"> Gallery</a></li>
								<li><a href="shop.html" class="slide-item"> Shop</a></li>
								<li><a href="shop-cart.html" class="slide-item"> Shop Cart</a></li>
								<li><a href="terms.html" class="slide-item"> Terms and Conditions</a></li>
								<li><a href="register.html" class="slide-item"> Register</a></li>
								<li><a href="login.html" class="slide-item"> Login</a></li>
								<li><a href="forgot.html" class="slide-item"> Forgot Password</a></li>
								<li><a href="reset.html" class="slide-item"> Reset Password</a></li>
								<li><a href="under-construction.html" class="slide-item"> Under Construction</a></li>
								<li><a href="lockscreen.html" class="slide-item"> Lock Screen</a></li>
								<li><a href="404.html" class="slide-item"> 404</a></li>
								<li><a href="505.html" class="slide-item"> 505</a></li>
								<li><a href="emptypage.html" class="slide-item"> Empty  Page</a></li>
							</ul>
						</li>
						---}}
					</ul>
				</aside>

resources/views/esquema/pie_pagina.blade.php
                <footer class="main-footer">
					<div class="text-center">
						Copyright &copy; Area51 @php echo date('Y') @endphp. Design By<a target="_blank" href="https://www.facebook.com/leopalima"> LeoPalima</a>
					</div>
				</footer>